### PR TITLE
Adds Access-Control-Allow-Origin header

### PR DESCRIPTION
**Pull request by fabianperez**
Obviously set to *. Deal with it 😎

### CODE REVIEW

**Comment by fabianperez** [comment]
Wait no. I meant to open this against my repo

**Comment by fabianperez** [comment]
how do i use github

**Comment by atmos** [comment]
It's ok bud. The new design is confusing af. :sunglasses:

**Comment by fabianperez** [comment]
thank you for this open source gift, based god.

**Comment by atmos** [comment]
> man I have turned emo its very fun and relaxing.
> plus you don't get excited about anything
[- Lil B](https://twitter.com/LILBTHEBASEDGOD/status/1944589439)

**Pull request closed without merging**
