### PR TITLE
Accept all valid images regardless of HTTP status

### LINKED ISSUE #75: Forward image when valid Content-Type & body
Some services return a 404 or 5xx *with an image*. This can be used e.g. for default / fallback images and it's totally legitimate to do so.

I think camo should proxy **all valid images regardless of the HTTP status** – this is what Browsers do as well (or intend to, see [chromium-464515](https://code.google.com/p/chromium/issues/detail?id=464515)).

I'd be happy to make a PR if you agree.

### PR DESCRIPTION
**Pull request by jomo**
fixes #75.

0. I have also added a test for this (tests 404 only).
0. `OpenSSL::Digest::Digest` has been replaced with `OpenSSL::Digest` due to ruby/ruby#446

Let me know if any changes are required.

### CODE REVIEW

**Comment by atmos** [comment]
Do you know of any images off-hand that should exhibit this behavior if we deployed it live?

**Comment by jomo** [comment]
Currently you can use https://crafatar.com/avatars/0
*(this will change to 200 OK at some point in future)*

**Comment by jomo** [comment]
`img`:
img

seems to be working :)

**Comment by atmos** [comment]
@jomo I'm leaving this out in production for the time being while I wait on our security team to review it and let me know if I'm overlooking any security related aspects that would prevent me from merging this.

Thanks.

**Comment by jomo** [comment]
:+1:

On March 24, 2015 6:11:53 PM CET, Corey Donohoe <notifications@github.com> wrote:
>@jomo I'm leaving this out in production for the time being while I
>wait on our security team to review it and let me know if I'm
>overlooking any security related aspects that would prevent me from
>merging this.
>
>Thanks.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/atmos/camo/pull/77#issuecomment-85604116

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jomo** [comment]
Okay, so I was bored: https://img-any-status.herokuapp.com/ - happy testing!












Seems like 304 is hanging forever (screenshot)[https://i.imgur.com/GBMlRYh.png)

**Comment by atmos** [comment]
@jomo this has been out in production for a bit but I see pretty consistent images failing to load. My hunch is the combination of fastly, our cdn, and the non-2XX response codes are causing the errors. What's weird is it seems to work pretty consistently after a refresh.

**Comment by jomo** [comment]
> images failing to load

What exactly does that mean? Are they not showing in the browser? Or are they not sent to the browser?

> combination of fastly and non-2XX codes

Maybe we could just return a 200 OK instead of forwarding the status code?

> seems to work pretty consistently after a refresh

Is that with all images or with the images in my comment above? In case of the latter, that's just [heroku rebooting the app](https://blog.heroku.com/archives/2013/6/20/app_sleeping_on_heroku)

**Comment by atmos** [comment]
camo 2015-04-03 11-02-48

So that's what happened when I just opened up this issue.

> Maybe we could just return a 200 OK instead of forwarding the status code?

I feel like that's lying, I dunno. What does chrome do in this situation?

**Comment by jomo** [comment]
It's just a [bug in chrome](https://code.google.com/p/chromium/issues/detail?id=464515). Apparently Firefox does something similar, but the images show up in Safari.

That's definitely a browser thing though.

**Comment by atmos** [comment]
> That's definitely a browser thing though.

Camo *is* a browser thing at it's core though. It's not to be pedantic, but it's whole purpose is to be nice to the user. Intermittent loading errors aren't something I think I can accept.

**Comment by jomo** [comment]
What I mean is that images not ~~loading~~ displaying is a bug only in Chrome (and apparently Firefox). Camo forwards the images using the same status code, so this bug is completely unrelated to camo.
You can actually [open the images non-embedded](https://camo.githubusercontent.com/de3eecb178bbf6de1dd1fc3701c07f2666a9f330/68747470733a2f2f696d672d616e792d7374617475732e6865726f6b756170702e636f6d2f343034) and you'll see that both Chrome and Firefox load and display the images.
The images also won't show up if you embed them on [some other site](http://jsbin.com/kubacerefi/1/edit?html,output) that doesn't use camo.

If you really want to workaround this bug to "be nice to the user", then the only option is to always return `200 OK` but afaik camo's job is to proxy images through SSL, not to fix the end user's browser bugs.

**Comment by jomo** [comment]
Apparently Firefox only has this issue for SVG images. FYI, I just [filed a bug for that](https://bugzilla.mozilla.org/show_bug.cgi?id=1150993).

**Comment by atmos** [comment]
Thanks @jomo

**Pull request merged**
