### PR TITLE
Add CAMO_HASH option to allow customizing the hash used.

### PR DESCRIPTION
**Pull request by md-5**

### CODE REVIEW

**Comment by atmos** [comment]
Can you write a test for another hash as an example?

**Comment by md-5** [comment]
I will try.
I don't actually code ruby, but I could just copy-pasta the code.
Unless there is a way to make a paramatized test?

**Comment by md-5** [comment]
Actually not sure how to do this in a good way at all, given that the ruby tests require the cofeescript server to be already running.

**Comment by md-5** [comment]
If you want to test behaviour yourself, set hash to md5 and do so accordingly in the tests as well.

**Comment by rmm5t** [comment]
Is there really a benefit to having a feature to support any hashing algorithm? i.e. What's the use-case where sha1 isn't good enough?

**Comment by md-5** [comment]
@rmm5t another website I was using (XenForo) uses md5.
Although if you wanted you could just change the other software.

**Comment by rmm5t** [comment]
@md-5 What does forum software have anything to do with the interface to an SSL image proxy?  

:-1:

**Comment by md-5** [comment]
@rmm5t different pre-existing softwares may use different hashes. In this case it would be beneficial to allow the selection of a different hash to enable compatibility with such software.

**Comment by rmm5t** [comment]
> different pre-existing softwares may use different hashes. In this case it would be beneficial to allow the selection of a different hash to enable compatibility with such software.

@md-5 That argument doesn't really hold water with me. I expected your desired use-case to be that you wanted to use a more secure hashing algorithm than sha1 (like sha256 or sha512), not a less secure algorithm (md5). I'd argue that more secure hashing isn't necessary for a service like camo, but I was curious about possibly a different use case. 

You mentioned you were using XenForo (PHP forum software). Camo has it's own URL format and digesting path structure that other software isn't necessarily going to automatically handle for SSL image proxying. No matter what you choose, there's going to be some custom integration, and it's better to stick with Camo's default, IMO.

Since you're using PHP, `md5` vs `sha1` digests are trivial:

```php
md5("foobar")
// vs
sha1("foobar")
```

http://php.net/manual/en/function.md5.php
http://php.net/manual/en/function.sha1.php

The desire for customizing the hashing algorithm still sounds unwarranted to me.

**Comment by atmos** [comment]
Looking at this I'm seeing two things that make me think this PR is unnecessary.

* Introducing this new behavior makes it difficult to test w/o restarting the server process w/ different hash environmental variables. 
* SHA1 is pretty common and available on most modern languages. 

I'm unaware of other apps having custom support for camo itself so if you're extending functionality to support camo you can probably use sha1.

**Pull request closed without merging**
