### PR TITLE
Support case insensitive MIME Types per RFC 2046 - Fixes #79

### LINKED ISSUE #79: Camo not compliant with RFC2046 on case insensitivity
I saw this error in our logs:
Non-Image content-type returned 'image/JPEG'

The code doesn't appear to take case insensitivity of MIME Types into account.
https://github.com/atmos/camo/blob/7af31a0eda6d602111c857a007564a4f3f095185/server.coffee#L165

Nor does the mime-types.json, but I don't recommend adding all permutations of case there.

http://tools.ietf.org/html/rfc2046#section-4.2
4.2.  Image Media Type

   A media type of "image" indicates that the body contains an image.
   The subtype names the specific image format.  These names are not
   case sensitive. An initial subtype is "jpeg" for the JPEG format
   using JFIF encoding [JPEG]

### PR DESCRIPTION
**Pull request by kereyroper**

### CODE REVIEW

**Comment by adepue** [comment]
Thanks @atmos!  Can we get a new version tagged for release?  Just curious.

**Comment by atmos** [comment]
I don't have a proper dev environment setup right now, but if you can make a PR bumping the coffee script, package.json, and generated js I can apply it via the web.

**Comment by joyce** [comment]
hey @atmos , can we get the new version tagged for release? thanks!

**Comment by atmos** [comment]
Version 2.3.0 was tagged in #81

**Comment by joyce** [comment]
sweet just saw it. thanks!

**Pull request merged**
