### PR TITLE
Add links to examples in readme

### PR DESCRIPTION
**Pull request by willwashburn**
I'm thinking it could be useful having a running list of clients for creating the urls in the readme. Something like this would have helped me when I first started/setup camo.

### CODE REVIEW

**Comment by rmm5t** [comment]
I don't think "Clients" is the correct word to use, because these are
really just libraries that facilitate generating signed image URLs.  Plus,
there is already a wiki page dedicated to this. Please consider adding a
PHP section:

https://github.com/atmos/camo/wiki/Generating-Signed-Image-URLs

I don't think the readme should be polluted with too much of this, but it
might be nice to just link to the wiki page from the readme.

**Comment by atmos** [comment]
TIL this repo has a wiki.

**Comment by willwashburn** [comment]
@rmm5t Word. Apologizes for the "client" misnomer.

I think you're right this is probably better placed in the wiki and that there should just be a link from the readme to it. 

For what its worth I never saw the wiki when I was getting started -- it would have been useful.

Better to just make a new PR with that or use this one?

**Comment by atmos** [comment]
I'd just rename the Clients part to examples or something.

**Pull request merged**
